### PR TITLE
PODAUTO-267: 4.19 release chores

### PR DESCRIPTION
**Pull request by maxcao13**
```
sed -i '/^replace / d' go.mod
sed -i 's/4\.18/4.19/g' Makefile hack/update-vendor.sh images/ci/Dockerfile images/operator-registry/Dockerfile.registry.ci manifests/art.yaml manifests/clusterresourceoverride-operator.package.yaml manifests/stable/clusterresourceoverride-operator.clusterserviceversion.yaml manifests/stable/image-references
sed -i 's/1\.22/1.23/g' images/ci/Dockerfile
sed -i 's/v0.31.2/v0.32.0/' hack/update-vendor.sh
go get -u github.com/openshift/build-machinery-go
go mod tidy
go mod  vendor
```

* Manually updated `images/operator-registry/Dockerfile.registry.ci` to `quay.io/operator-framework/upstream-registry-builder:v1.32.0`
* Manually updated `images/dev/Dockerfile.dev` to `registry.access.redhat.com/ubi9-minimal:9.5`

### CODE REVIEW

**Comment by maxcao13** [comment]
Depends on: https://github.com/openshift/release/pull/59985#issuecomment-2549622268

**Comment by maxcao13** [comment]
Hm... well it keeps failing because it seems the build root image keeps trying to use `golang-1.22`. I guess we have to merge the `ci-operator.yaml` change first like what happens when ART requests a PR?... :/

**Comment by joelsmith** [comment]
I think that https://github.com/openshift/cluster-resource-override-admission-operator/blob/16814488ce180b18b971f7866b47969de708a868/images/ci/Dockerfile#L1 is the culprit here. I'd guess that after that is updated to 1.23 and added to this PR, the images test will pass.

**Comment by maxcao13** [comment]
Whoops, thanks for catching that. Guess I'll update the sed commands in the PR...

**Comment by maxcao13** [comment]
Seemed to work! But now it's just breaking regularly, so I'll take a look at that.

**Comment by maxcao13** [comment]
I'm not 100% sure this is the problem, but it seems from testing that the operator is constantly comparing the deployment `generation` to the `deployment.status.generation` and it keeps seeing that they are unequal. And I'm guessing that when we update the deployment prior to that check, the reconciler is now too fast and doesn't notice the deployment controller's observed generation change that happens after the check. I'm guessing some optimizations were made somewhere in the 0.32 upgrade somewhere, but again not 100% sure.

So now I've changed in latest: since we do this generation check 3 times in the entire loop (once at [beginning](https://github.com/openshift/cluster-resource-override-admission-operator/blob/f84efa8b47753396c44a8439164525aac47ed2be/pkg/clusterresourceoverride/internal/reconciler/reconciler.go#L29), once at [end](https://github.com/openshift/cluster-resource-override-admission-operator/blob/f84efa8b47753396c44a8439164525aac47ed2be/pkg/clusterresourceoverride/internal/reconciler/reconciler.go#L37), and once [right after we ensure the deployment](https://github.com/openshift/cluster-resource-override-admission-operator/blob/f84efa8b47753396c44a8439164525aac47ed2be/pkg/clusterresourceoverride/internal/reconciler/reconciler.go#L34)), then I think it's okay if we only check the generation at the beginning and end.

**Comment by joelsmith** [comment]
That seems like a great way to cut down on flakes. I'm always a fan of getting rid of bad tests especially ones which rely on timing. Thanks for taking care of the 4.19 chores!

/lgtm

**Pull request merged**
