### PR TITLE
OCPBUGS-30563: Add required feature labels

### PR DESCRIPTION
**Pull request by joelsmith**

### CODE REVIEW

**Comment by joelsmith** [comment]
/hold
Trying to figure out whether VPA is FIPS compliant or not

**Comment by joelsmith** [comment]
Something strange is going on with the operand image in the e2e tests. The operator is running, but when it runs the operand, the pod goes into crash loop backoff with this in the logs:
```
/usr/bin/cluster-resource-override-admission: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /usr/bin/cluster-resource-override-admission)
/usr/bin/cluster-resource-override-admission: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/cluster-resource-override-admission)
```

**Comment by joelsmith** [comment]
/hold cancel
Tested with https://github.com/openshift/check-payload to show that it passes all our FIPS compliance checks.
Tested 4.15 operator and operand images:
```
$ sudo ./check-payload scan operator --spec brew.registry.redhat.io/openshift4/ose-clusterresourceoverride-rhel9-operator@sha256:1d9850d539cc5dc7e34b1a351c455b9db678c74ef150cbd2cbf373e46d2339ad
...
---- Successful run
$ sudo ./check-payload scan operator --spec brew.registry.redhat.io/openshift4/ose-clusterresourceoverride-rhel9@sha256:1a7709c5a2e8dc86a15438ca1e8c7515c18b97360a46e7e4c2268a95e86948459c1e
...
---- Successful run
```

**Comment by joelsmith** [comment]
/retest
Now that https://github.com/openshift/cluster-resource-override-admission/pull/68 has merged, perhaps the e2e tests can pass.

**Comment by jkyros** [comment]
Awesome, it passed. :smile: 
/lgtm

**Pull request merged**
