### PR TITLE
add ppc64le arch label to CRO

### PR DESCRIPTION
**Pull request by snehakpersistent**
Add ppc64le arch label to make CRO operator visible in OperatorHub on ppc64le platform.

### CODE REVIEW

**Comment by jrvaldes** [comment]
> Add ppc64le arch label to make CRO operator visible in OperatorHub on ppc64le platform.

@snehakpersistent  I recommend adding this to the commit message as well. Having the  `what` and `why` the changes in the commit messages are very helpful.

**Comment by jrvaldes** [comment]
@rphillips  Does the addition of a newly supported architecture need to be documented elsewhere? A section in the Readme file, [official docs](https://docs.openshift.com/container-platform/4.12/nodes/clusters/nodes-cluster-overcommit.html#nodes-cluster-resource-override_nodes-cluster-overcommit), etc. ?

**Comment by snehakpersistent** [comment]
@jrvaldes I have updated the commit message. Please trigger the CI builds.

**Comment by jrvaldes** [comment]
LGTM, will defer to @rphillips and/or @joelsmith  for final sign-off and feedback on https://github.com/openshift/cluster-resource-override-admission-operator/pull/101#issuecomment-1428821609

**Comment by snehakpersistent** [comment]
@rphillips @joelsmith can you please review this?

**Comment by joelsmith** [comment]
Thanks!
/retest
/lgtm

**Comment by jrvaldes** [comment]
@joelsmith   PTAL at https://github.com/openshift/cluster-resource-override-admission-operator/pull/101#issuecomment-1428821609

**Pull request merged**
