### PR TITLE
bump manifests for 4.5

### PR DESCRIPTION
**Pull request by rphillips**
Fixes Issue #25

### CODE REVIEW

**Comment by tkashem** [comment]
I think we need to rename https://github.com/openshift/cluster-resource-override-admission-operator/tree/master/manifests/4.4 to `4.5` as well.

**Comment by tkashem** [comment]
The Makefile needs to point to the new version after the rename - https://github.com/openshift/cluster-resource-override-admission-operator/blob/master/Makefile#L16

**Comment by tkashem** [comment]
art.yaml needs to change as well - https://github.com/openshift/cluster-resource-override-admission-operator/blob/master/manifests/art.yaml
I wish it were an automated process.

**Comment by rphillips** [comment]
`api.ci-op-4tyk3nl9-8f9b1.origin-ci-int-aws.dev.rhcloud.com:6443 was refused`

/test e2e-aws-olm

**Pull request merged**
