### PR TITLE
Bug 2086754: [ART-4049] Bump to 4.11

### PR DESCRIPTION
**Pull request by locriandev**
[Test build](https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=45334851) passed
Ref. [ART-4049](https://issues.redhat.com/browse/ART-4049)

### CODE REVIEW

**Comment by haircommander** [comment]
/retitle Bug 2073076: [ART-4049] Bump to 4.11

**Review by QiWang19 — COMMENTED** [review]
`manifests/stable/clusterresourceoverride.crd.yaml` should this be `manifests/4.11/clusterresourceoverride.crd.yaml` for passing the CI? The Makefile still has `manifests/$(VERSION)/clusterresourceoverride.crd.yaml`

**Comment by locriandev** [comment]
> `manifests/stable/clusterresourceoverride.crd.yaml` should this be `manifests/4.11/clusterresourceoverride.crd.yaml` for passing the CI? The Makefile still has `manifests/$(VERSION)/clusterresourceoverride.crd.yaml`

Good catch! Makefile needs to be fixed, we intend to use stable channel

**Comment by locriandev** [comment]
> > Good catch! Makefile needs to be fixed, we intend to use stable channel
> 
> @locriandev will you fix the Makefile and rebase this PR?

I will be on sick leave for a couple of days, then I intend to do so

**Comment by QiWang19** [comment]
@locriandev would you mind I take over this PR?

**Comment by locriandev** [comment]
> @locriandev would you mind I take over this PR?

Please go ahead

**Comment by haircommander** [comment]
/lgtm

@QiWang19 @rphillips PTAL

**Review by QiWang19 — COMMENTED** [review]
LGTM

**Pull request merged**
