### PR TITLE
Bug 1923802: Update yq commands

### PR DESCRIPTION
**Pull request by ehashman**
/hold

### CODE REVIEW

**Comment by ehashman** [comment]
e2e-aws flaked.
e2e-aws-olm looks like a legit failure:

```
+ sed 's,CLUSTERRESOURCEOVERRIDE_OPERAND_IMAGE,"registry.build01.ci.openshift.org/ci-op-vtvg1wsd/stable:cluster-resource-override-admission",g' -i ./_output/olm/registry/registry-deployment.yaml
./hack/deploy-operator-registry.sh clusterresourceoverride-operator /cli/oc ""./_output"/olm/registry"
setting up namespace
namespace/clusterresourceoverride-operator created
applying configmap
configmap/clusterresourceoverride-operator-registry-env created
creating deployment
Error: unknown command "r" for "yq"
Run 'yq --help' for usage.
could not retrieve Deployment name from ./_output/olm/registry/registry-deployment.yaml
make: *** [operator-registry-deploy] Error 1
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-02-01T22:05:49Z"}
error: failed to execute wrapped command: exit status 2
```

**Comment by ehashman** [comment]
/cc @rphillips 

assuming the olm CI passes now :)

**Comment by rphillips** [comment]
@ehashman we should add a new BZ to this one.

**Pull request merged**
